//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpServerEngineSampleClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\Daniel\\dev\\Client-SQ" +
            "L.mdf;Integrated Security=True;Connect Timeout=30")]
        public string Client_SQL_DB2ConnectionString {
            get {
                return ((string)(this["Client_SQL_DB2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NEWWINDOWS\\SQLEXPRESS;Initial Catalog=c:\\users\\daniel\\dev\\Client-SQL." +
            "mdf;Integrated Security=True")]
        public string c__users_daniel_dev_Client_SQL_mdfConnectionString {
            get {
                return ((string)(this["c__users_daniel_dev_Client_SQL_mdfConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NEWWINDOWS\\SQLEXPRESS;Initial Catalog=Client-SQL;Integrated Security=" +
            "True")]
        public string Client_SQLConnectionString {
            get {
                return ((string)(this["Client_SQLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NEWWINDOWS\\SQLEXPRESS;Initial Catalog=Client-SQL2;Integrated Security" +
            "=True")]
        public string Client_SQL2ConnectionString {
            get {
                return ((string)(this["Client_SQL2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int func1_type {
            get {
                return ((int)(this["func1_type"]));
            }
            set {
                this["func1_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int func1_port {
            get {
                return ((int)(this["func1_port"]));
            }
            set {
                this["func1_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int func2_type {
            get {
                return ((int)(this["func2_type"]));
            }
            set {
                this["func2_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int func2_port {
            get {
                return ((int)(this["func2_port"]));
            }
            set {
                this["func2_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int func3_type {
            get {
                return ((int)(this["func3_type"]));
            }
            set {
                this["func3_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int func3_port {
            get {
                return ((int)(this["func3_port"]));
            }
            set {
                this["func3_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DESK_LIGHT {
            get {
                return ((bool)(this["DESK_LIGHT"]));
            }
            set {
                this["DESK_LIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EAST_LIGHT {
            get {
                return ((bool)(this["EAST_LIGHT"]));
            }
            set {
                this["EAST_LIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NORTHWEST_LIGHT {
            get {
                return ((bool)(this["NORTHWEST_LIGHT"]));
            }
            set {
                this["NORTHWEST_LIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SOUTHEAST_LIGHT {
            get {
                return ((bool)(this["SOUTHEAST_LIGHT"]));
            }
            set {
                this["SOUTHEAST_LIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MIDDLE_LIGHT {
            get {
                return ((bool)(this["MIDDLE_LIGHT"]));
            }
            set {
                this["MIDDLE_LIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WEST_LIGHT {
            get {
                return ((bool)(this["WEST_LIGHT"]));
            }
            set {
                this["WEST_LIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NORTHEAST_LIGHT {
            get {
                return ((bool)(this["NORTHEAST_LIGHT"]));
            }
            set {
                this["NORTHEAST_LIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SOUTHWEST_LIGHT {
            get {
                return ((bool)(this["SOUTHWEST_LIGHT"]));
            }
            set {
                this["SOUTHWEST_LIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BENCH_24V_1 {
            get {
                return ((bool)(this["BENCH_24V_1"]));
            }
            set {
                this["BENCH_24V_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BENCH_24V_2 {
            get {
                return ((bool)(this["BENCH_24V_2"]));
            }
            set {
                this["BENCH_24V_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BENCH_12V_1 {
            get {
                return ((bool)(this["BENCH_12V_1"]));
            }
            set {
                this["BENCH_12V_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BENCH_12V_2 {
            get {
                return ((bool)(this["BENCH_12V_2"]));
            }
            set {
                this["BENCH_12V_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BENCH_5V_1 {
            get {
                return ((bool)(this["BENCH_5V_1"]));
            }
            set {
                this["BENCH_5V_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BENCH_5V_2 {
            get {
                return ((bool)(this["BENCH_5V_2"]));
            }
            set {
                this["BENCH_5V_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BENCH_3V3_1 {
            get {
                return ((bool)(this["BENCH_3V3_1"]));
            }
            set {
                this["BENCH_3V3_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BENCH_3V3_2 {
            get {
                return ((bool)(this["BENCH_3V3_2"]));
            }
            set {
                this["BENCH_3V3_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BENCH_LIGHT1 {
            get {
                return ((bool)(this["BENCH_LIGHT1"]));
            }
            set {
                this["BENCH_LIGHT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BENCH_LIGHT2 {
            get {
                return ((bool)(this["BENCH_LIGHT2"]));
            }
            set {
                this["BENCH_LIGHT2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CABIN1 {
            get {
                return ((bool)(this["CABIN1"]));
            }
            set {
                this["CABIN1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CABIN2 {
            get {
                return ((bool)(this["CABIN2"]));
            }
            set {
                this["CABIN2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CABIN3 {
            get {
                return ((bool)(this["CABIN3"]));
            }
            set {
                this["CABIN3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CABIN4 {
            get {
                return ((bool)(this["CABIN4"]));
            }
            set {
                this["CABIN4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CABIN5 {
            get {
                return ((bool)(this["CABIN5"]));
            }
            set {
                this["CABIN5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CABIN6 {
            get {
                return ((bool)(this["CABIN6"]));
            }
            set {
                this["CABIN6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CABIN7 {
            get {
                return ((bool)(this["CABIN7"]));
            }
            set {
                this["CABIN7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CABIN8 {
            get {
                return ((bool)(this["CABIN8"]));
            }
            set {
                this["CABIN8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COOP1_LIGHT {
            get {
                return ((bool)(this["COOP1_LIGHT"]));
            }
            set {
                this["COOP1_LIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COOP1_HEATER {
            get {
                return ((bool)(this["COOP1_HEATER"]));
            }
            set {
                this["COOP1_HEATER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COOP2_LIGHT {
            get {
                return ((bool)(this["COOP2_LIGHT"]));
            }
            set {
                this["COOP2_LIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COOP2_HEATER {
            get {
                return ((bool)(this["COOP2_HEATER"]));
            }
            set {
                this["COOP2_HEATER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WATER_HEATER {
            get {
                return ((bool)(this["WATER_HEATER"]));
            }
            set {
                this["WATER_HEATER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BATTERY_HEATER {
            get {
                return ((bool)(this["BATTERY_HEATER"]));
            }
            set {
                this["BATTERY_HEATER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WATER_PUMP {
            get {
                return ((bool)(this["WATER_PUMP"]));
            }
            set {
                this["WATER_PUMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WATER_VALVE1 {
            get {
                return ((bool)(this["WATER_VALVE1"]));
            }
            set {
                this["WATER_VALVE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WATER_VALVE2 {
            get {
                return ((bool)(this["WATER_VALVE2"]));
            }
            set {
                this["WATER_VALVE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WATER_VALVE3 {
            get {
                return ((bool)(this["WATER_VALVE3"]));
            }
            set {
                this["WATER_VALVE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OUTDOOR_LIGHT1 {
            get {
                return ((bool)(this["OUTDOOR_LIGHT1"]));
            }
            set {
                this["OUTDOOR_LIGHT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OUTDOOR_LIGHT2 {
            get {
                return ((bool)(this["OUTDOOR_LIGHT2"]));
            }
            set {
                this["OUTDOOR_LIGHT2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool silent_mode {
            get {
                return ((bool)(this["silent_mode"]));
            }
            set {
                this["silent_mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int func4_type {
            get {
                return ((int)(this["func4_type"]));
            }
            set {
                this["func4_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int func4_port {
            get {
                return ((int)(this["func4_port"]));
            }
            set {
                this["func4_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int func5_type {
            get {
                return ((int)(this["func5_type"]));
            }
            set {
                this["func5_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int func5_port {
            get {
                return ((int)(this["func5_port"]));
            }
            set {
                this["func5_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNUSED150_1 {
            get {
                return ((bool)(this["UNUSED150_1"]));
            }
            set {
                this["UNUSED150_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNUSED150_2 {
            get {
                return ((bool)(this["UNUSED150_2"]));
            }
            set {
                this["UNUSED150_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNUSED150_3 {
            get {
                return ((bool)(this["UNUSED150_3"]));
            }
            set {
                this["UNUSED150_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNUSED150_4 {
            get {
                return ((bool)(this["UNUSED150_4"]));
            }
            set {
                this["UNUSED150_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNUSED150_5 {
            get {
                return ((bool)(this["UNUSED150_5"]));
            }
            set {
                this["UNUSED150_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNUSED150_6 {
            get {
                return ((bool)(this["UNUSED150_6"]));
            }
            set {
                this["UNUSED150_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNUSED150_7 {
            get {
                return ((bool)(this["UNUSED150_7"]));
            }
            set {
                this["UNUSED150_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNUSED150_8 {
            get {
                return ((bool)(this["UNUSED150_8"]));
            }
            set {
                this["UNUSED150_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNUSED150_9 {
            get {
                return ((bool)(this["UNUSED150_9"]));
            }
            set {
                this["UNUSED150_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNUSED150_10 {
            get {
                return ((bool)(this["UNUSED150_10"]));
            }
            set {
                this["UNUSED150_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool play_chimes {
            get {
                return ((bool)(this["play_chimes"]));
            }
            set {
                this["play_chimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Quote_iter {
            get {
                return ((int)(this["Quote_iter"]));
            }
            set {
                this["Quote_iter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Factoid_iter {
            get {
                return ((int)(this["Factoid_iter"]));
            }
            set {
                this["Factoid_iter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort ds_server {
            get {
                return ((ushort)(this["ds_server"]));
            }
            set {
                this["ds_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort ds_150 {
            get {
                return ((ushort)(this["ds_150"]));
            }
            set {
                this["ds_150"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort ds_154 {
            get {
                return ((ushort)(this["ds_154"]));
            }
            set {
                this["ds_154"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort ds_147 {
            get {
                return ((ushort)(this["ds_147"]));
            }
            set {
                this["ds_147"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort ds_145 {
            get {
                return ((ushort)(this["ds_145"]));
            }
            set {
                this["ds_145"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort ds_151 {
            get {
                return ((ushort)(this["ds_151"]));
            }
            set {
                this["ds_151"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asdf {
            get {
                return ((string)(this["asdf"]));
            }
            set {
                this["asdf"] = value;
            }
        }
    }
}
